version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

formatters:
  enable:
    - gofumpt
    - goimports

linters:
  default: standard
  enable:
    - goconst # Find repeated strings that could be constants
    - gocyclo # Check cyclomatic complexity
    - misspell # Fix common spelling mistakes
    - unconvert # Remove unnecessary type conversions
    - unparam # Find unused function parameters
    - dupl # Find duplicated code

    - bodyclose # Check HTTP response body is closed
    - gosec # Security checks
    - rowserrcheck # Check sql.Rows.Err is checked
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed

    - errname # Check error naming conventions
    - errorlint # Find misuse of error wrapping
    - nilerr # Find incorrect nil error returns

    - contextcheck
    - containedctx

  settings:
    goconst:
      min-len: 3
      min-occurrences: 3

    errcheck:
      check-type-assertions: true

    govet:
      disable:
        - shadow

  exclusions:
    rules:
      - path: ".*_test\\.go$"
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
          - goconst
    paths:
      - "db/sqlc/.*"
      - "internal/ui/.*_templ\\.go$"
      - "internal/ui/templui/.*"
      - "internal/ui/utils/templui\\.go$"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
