version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: standard
  enable:
    - goconst # Find repeated strings that could be constants
    - gocyclo # Check cyclomatic complexity
    - misspell # Fix common spelling mistakes
    - unconvert # Remove unnecessary type conversions
    - unparam # Find unused function parameters
    - dupl # Find duplicated code

    - bodyclose # Check HTTP response body is closed
    - gosec # Security checks
    - rowserrcheck # Check sql.Rows.Err is checked
    - sqlclosecheck # Check sql.Rows and sql.Stmt are closed

    - errname # Check error naming conventions
    - errorlint # Find misuse of error wrapping
    - nilerr # Find incorrect nil error returns

    - contextcheck
    - containedctx

linters-settings:
  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - shadow

issues:
  max-issues-per-linter: 0

  max-same-issues: 0

  # Exclude some linters from test files and generated files
  exclude-rules:
    - path: ".*_test.go$"
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst
    # Exclude generated files from all linters
    - path: "db/sqlc/.*"
    - path: "internal/ui/.*_templ.go"
    - path: "internal/ui/templui/.*"
    - path: "internal/ui/utils/templui.go"
