services:
  app:
    image: gowatch:latest
    container_name: gowatch
    ports:
      - "8080:8080"
    environment:
      - TMDB_API_KEY=YOUR_TMDB_API_KEY
      - SERVER_PORT=8080
      - REQUEST_TIMEOUT=30s
      - DB_PATH=/app/data
      - DB_NAME=gowatch.db
      - LOG_LEVEL=INFO
      - LOG_FILE=tmp/log.json
    volumes:
      - ./data:/app/data
    restart: unless-stopped
