// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/marcosalvi-01/gowatch/db/types/date"
)

type Cast struct {
	MovieID   int64
	PersonID  int64
	CastID    int64
	CreditID  string
	Character string
	CastOrder int64
	UpdatedAt *time.Time
}

type Crew struct {
	MovieID    int64
	PersonID   int64
	CreditID   string
	Job        string
	Department string
	UpdatedAt  *time.Time
}

type Genre struct {
	ID        int64
	Name      string
	UpdatedAt *time.Time
}

type GenreMovie struct {
	MovieID   int64
	GenreID   int64
	UpdatedAt *time.Time
}

type List struct {
	ID           int64
	Name         string
	CreationDate string
	Description  *string
	UserID       *int64
	IsWatchlist  bool
}

type ListMovie struct {
	MovieID   int64
	ListID    int64
	DateAdded string
	Position  *int64
	Note      *string
}

type Movie struct {
	ID               int64
	Title            string
	OriginalTitle    string
	OriginalLanguage string
	Overview         string
	ReleaseDate      date.Date
	PosterPath       string
	BackdropPath     string
	Popularity       float64
	VoteCount        int64
	VoteAverage      float64
	Budget           int64
	Homepage         string
	ImdbID           string
	Revenue          int64
	Runtime          int64
	Status           string
	Tagline          string
	UpdatedAt        *time.Time
}

type Person struct {
	ID                 int64
	Name               string
	OriginalName       string
	ProfilePath        string
	KnownForDepartment string
	Popularity         float64
	Gender             int64
	Adult              bool
	UpdatedAt          *time.Time
}

type Session struct {
	ID        string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt *time.Time
}

type User struct {
	ID                    int64
	Email                 string
	PasswordHash          string
	Name                  string
	CreatedAt             *time.Time
	Admin                 bool
	PasswordResetRequired bool
}

type Watched struct {
	ID               int64
	MovieID          int64
	UserID           *int64
	WatchedDate      date.Date
	WatchedInTheater bool
	Rating           *float64
}
